In [3]:
import pandas as pd

In [5]:
df_clientes = pd.read_csv('Clientes.csv')

In [7]:
df_clientes

,ClienteID,Nombre,Apellido,email,NúmeroIdentidad,Teléfono,FechaNacimiento,TarjetaCredito
0,1,Ema,Espine,eespine0@de.vu,136691591-7,505-821-5536,7/23/1998,3.538210e+15
1,2,Aileen,Cissell,acissell1@webnode.com,924683794-0,421-862-6029,5/27/1992,3.038220e+13
2,3,Joella,Miquelet,jmiquelet2@skype.com,441901707-4,526-434-4995,04/04/1981,5.366410e+15
3,4,Orton,Lavers,olavers3@about.me,603622000-6,785-421-3186,9/13/1983,3.558250e+15
4,5,Onida,Van Arsdale,ovanarsdale4@tripod.com,480691491-6,812-989-6184,10/10/1985,6.333540e+15
...,...,...,...,...,...,...,...,...
995,996,Raynard,Noir,rnoirrn@craigslist.org,953702233-1,824-107-8035,6/18/1999,2.018330e+14
996,997,Keane,Dartan,kdartanro@nyu.edu,777546932-3,119-433-6434,1/19/1986,3.574750e+15
997,998,Renard,Cookson,rcooksonrp@simplemachines.org,209274846-7,911-510-1384,03/09/1994,3.005780e+13
998,999,Sayre,Danilenko,sdanilenkorq@canalblog.com,194962009-3,141-564-2456,3/14/1991,2.017390e+14
999,1000,Lotti,Pfeiffer,lpfeifferrr@icq.com,313474675-1,979-813-4434,9/29/1988,3.742890e+14

In [9]:
df_clientes= df_clientes.drop(columns=['ClienteID'])

In [11]:
df_clientes.to_csv('Clientes_modf.csv', index=False)

In [13]:
df_sucursales= pd.read_csv('Sucursales.csv')

In [15]:
df_sucursales

,SucursalID,Nombre,Dirección,Ciudad,Teléfono,Email
0,1,O,773 Canary Drive,Tegucigalpa,596-342-3586,leberle0@people.com.cn
1,2,F,643 Blackbird Lane,San Pedro Sula,546-616-9970,jsanham1@google.ca
2,3,I,78032 West Lane,Tegucigalpa,740-226-9201,vgold2@symantec.com
3,4,I,251 Roxbury Drive,Tegucigalpa,283-553-1085,cchinnock3@shareasale.com
4,5,C,009 Carioca Circle,Tegucigalpa,627-978-6284,jmegainey4@wikimedia.org
5,6,B,88 Florence Junction,San Pedro Sula,487-297-5769,swild5@cnn.com
6,7,F,3 Oxford Pass,Tegucigalpa,597-468-0969,thazlehurst6@ibm.com
7,8,E,50000 Bultman Center,Tegucigalpa,843-464-7195,htappin7@home.pl
8,9,A,5899 Lawn Court,Tegucigalpa,314-446-0599,mcramphorn8@storify.com
9,10,L,4 Anzinger Center,Tegucigalpa,452-347-6488,ckeyson9@intel.com
10,11,A,58 Esker Hill,Tegucigalpa,250-675-6268,fshawdfortha@live.com
11,12,O,9 Vernon Junction,Tegucigalpa,983-582-4708,aswainstonb@globo.com
12,13,A,5484 Straubel Plaza,Tegucigalpa,823-875-6199,hshrubbc@nature.com
13,14,C,6857 Utah Way,Tegucigalpa,386-368-0921,gtussained@51.la
14,15,B,036 Hollow Ridge Parkway,San Pedro Sula,392-271-7231,jvogle@stanford.edu

In [19]:
df_sucursales= df_sucursales.drop(columns=['SucursalID'])

In [21]:
df_sucursales.to_csv('sucursales_mod.csv', index= False)